import { defineConfig } from "vite";

export default defineConfig({
  build: {
    rollupOptions: {
      input: [
        "index.html", "pricing.html", "about.html", "security.html", "privacy.html", "ordlista-fakturahantering.html",
        "blog/index.html",
        "blog/vanliga-utmaningar-fakturahantering.html",
        "blog/bygg-transport-fakturor.html",
        "blog/fakturaformat.html",
        "blog/manuell-vs-automatiserad-fakturahantering.html",
        "blog/ocr-faktura.html",
        "blog/verifiera-leverantorsfakturor.html",
        "blog/what-is-invoice-processing.html",
        "blog/upptacka-feldebitering.html",
        "blog/automatiserad-fakturakontroll.html",
        "blog/checklista-fakturakontroll.html",
        "blog/fakturaflode.html",
        "blog/excel-vs-automatiserad-fakturahantering.html",
        "blog/fakturaattest.html",
        "blog/vanliga-fel-transportfakturor.html",
        "blog/roi-fakturaautomation.html",
        "blog/overdebitering-leverantorer.html",
        "blog/felaktig-leverantorsfaktura.html",
        "blog/minska-manuellt-arbete-fakturahantering.html",
        "blog/fakturakontroll-entreprenadprojekt.html",
        "blog/vanliga-fel-leverantorsfakturor.html",
        "blog/transportavtal-prislistor-fakturor.html",
        "blog/kontrollera-fakturor-mot-avtal.html",
        "blog/digital-dokumentanalys-fakturahantering.html",
        "blog/digital-document-analysis-invoice-processing.html",
        "blog/erp-integration-fakturahantering.html",
        "blog/ata-hantering-fakturakontroll.html",
        "blog/fakturafel-projektbudget-lonsamhet.html",
        "blog/intern-kontroll-leverantorsfakturor.html",
        "blog/upptacka-fakturabedrageri.html",
        "blog/infora-automatiserad-fakturakontroll.html",
        "news/index.html",
        "404.html",
      ],
    },
  },
});
